[colours]
fg = "#D3C6AA"
red = "#E67E80"
yellow = "#DBBC7F"
green = "#A7C080"
blue = "#7FBBB3"
purple = "#D699B6"
aqua = "#83C092"
orange = "#E69875"

grey_0 = "#7A8478"
grey_1 = "#859289"
grey_2 = "#9DA9A0"

bg_dim = "#1E2326"
bg_0 = "#272E33"
bg_1 = "#2E383C"
bg_2 = "#374145"
bg_3 = "#414B50"
bg_4 = "#495156"
bg_5 = "#4F5B58"

bg_red = "#493B40"
bg_yellow = "#45443C"
bg_green = "#3C4841"
bg_blue = "#384B55"
bg_purple = "#463F48"
bg_visual = "#4C3743"

[host_colours]
"adam-laptop" = "grey_0"
"homeserver" = "yellow"
"docker-vm" = "green"
"parents-server" = "aqua"
"parents-docker-vm" = "blue"
